#!/usr/bin/env bash
set -Eeuo pipefail

ENV_FILE=""
ENV_NAME="ext-liveks-fabric-e2e"
FABRIC_LOCATION="westus3"
FABRIC_CAPACITY_MODE="create"
FABRIC_CAPACITY_NAME=""
CLEANUP=false
KEEP_RESOURCES=false
NO_COLOR="${NO_COLOR:-}"
LOG_DIR=".deployment"
LOG_FILE=""
REPORT_PATH=""
export AZD_SKIP_FIRST_RUN="${AZD_SKIP_FIRST_RUN:-true}"

CHECK_IDS=(
  "external_login"
  "tools"
  "azd_env"
  "provision"
  "summary"
  "fabric_ids"
  "tables"
  "ontology_definition"
  "graph_model"
  "cleanup"
)
CHECK_LABELS=(
  "External tenant login is active"
  "Required local tools are available"
  "azd environment is prepared"
  "Fabric provisioner completes"
  "Fabric summary is generated"
  "Capacity, workspace, lakehouse, and ontology IDs are present"
  "Airline Ops tables are loaded"
  "Ontology definition is readable"
  "Ontology-backed GraphModel is queryable"
  "Fabric cleanup completes"
)
CHECK_STATUS=()
CHECK_NOTES=()

usage() {
  cat <<'USAGE'
Usage:
  bash scripts/fabric-e2e-test.sh --env-file .env.external.local --cleanup [options]

Options:
  --env-file <path>          Load external tenant env settings.
  --env-name <name>          azd environment name. Default: ext-liveks-fabric-e2e
  --fabric-location <region> Fabric capacity region. Default: westus3
  --capacity-mode <mode>     create or byo. Default: create
  --capacity-name <name>     Fabric capacity name. Required when --capacity-mode byo
  --cleanup                  Delete generated Fabric assets after validation.
  --keep-resources           Keep generated Fabric assets for debugging.
  --no-color                 Disable ANSI color output.
  -h, --help                 Show this help.
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --env-file) ENV_FILE="${2:-}"; shift 2 ;;
    --env-name) ENV_NAME="${2:-}"; shift 2 ;;
    --fabric-location) FABRIC_LOCATION="${2:-}"; shift 2 ;;
    --capacity-mode) FABRIC_CAPACITY_MODE="${2:-}"; shift 2 ;;
    --capacity-name) FABRIC_CAPACITY_NAME="${2:-}"; shift 2 ;;
    --cleanup) CLEANUP=true; shift ;;
    --keep-resources) KEEP_RESOURCES=true; shift ;;
    --no-color) NO_COLOR=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage >&2; exit 2 ;;
  esac
done

if [[ "$CLEANUP" == "true" && "$KEEP_RESOURCES" == "true" ]]; then
  echo "Choose either --cleanup or --keep-resources, not both." >&2
  exit 2
fi
case "$FABRIC_CAPACITY_MODE" in
  create|byo) ;;
  *) echo "Invalid --capacity-mode: $FABRIC_CAPACITY_MODE. Use create or byo." >&2; exit 2 ;;
esac
if [[ "$CLEANUP" != "true" && "$KEEP_RESOURCES" != "true" ]]; then
  echo "Pass --cleanup for full lifecycle validation or --keep-resources for debugging." >&2
  exit 2
fi

if [[ -t 1 && -z "$NO_COLOR" ]]; then
  C_RESET=$'\033[0m'; C_GREEN=$'\033[32m'; C_YELLOW=$'\033[33m'; C_RED=$'\033[31m'; C_BLUE=$'\033[34m'; C_DIM=$'\033[2m'
else
  C_RESET=""; C_GREEN=""; C_YELLOW=""; C_RED=""; C_BLUE=""; C_DIM=""
fi

for _id in "${CHECK_IDS[@]}"; do
  CHECK_STATUS+=("PENDING")
  CHECK_NOTES+=("")
done

mkdir -p "$LOG_DIR" "deployments/$ENV_NAME"
LOG_FILE="$LOG_DIR/fabric-e2e-${ENV_NAME}-$(date +%Y%m%d-%H%M%S).log"
REPORT_PATH="deployments/${ENV_NAME}/fabric-test-report.md"

log() { printf '%s\n' "$*" | tee -a "$LOG_FILE"; }

bar_for() {
  local done_count="$1"; local total="$2"; local width=28
  local filled=$(( done_count * width / total )); local empty=$(( width - filled ))
  printf '['; printf '%*s' "$filled" '' | tr ' ' '#'; printf '%*s' "$empty" '' | tr ' ' '-'; printf '] %d/%d' "$done_count" "$total"
}

check_index() {
  local id="$1"
  local i
  for (( i=0; i<${#CHECK_IDS[@]}; i++ )); do
    if [[ "${CHECK_IDS[$i]}" == "$id" ]]; then printf '%s' "$i"; return 0; fi
  done
  echo "Unknown check id: $id" >&2; exit 2
}

completed_count() {
  local count=0 status
  for status in "${CHECK_STATUS[@]}"; do
    case "$status" in PASS|FAIL|SKIP) count=$(( count + 1 )) ;; esac
  done
  printf '%s' "$count"
}

fail_count() {
  local count=0 status
  for status in "${CHECK_STATUS[@]}"; do [[ "$status" == "FAIL" ]] && count=$(( count + 1 )); done
  printf '%s' "$count"
}

escape_md() { printf '%s' "$1" | tr '\n' ' ' | sed 's/|/\\|/g'; }

write_report() {
  local completed total progress now
  completed="$(completed_count)"; total="${#CHECK_IDS[@]}"; progress="$(bar_for "$completed" "$total")"; now="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  {
    printf '# Fabric E2E Test Report\n\n'
    printf 'Generated by `scripts/fabric-e2e-test.sh`. This file is ignored by git.\n\n'
    printf -- '- Environment: `%s`\n' "$ENV_NAME"
    printf -- '- Fabric location: `%s`\n' "$FABRIC_LOCATION"
    printf -- '- Fabric capacity mode: `%s`\n' "$FABRIC_CAPACITY_MODE"
    printf -- '- Cleanup requested: `%s`\n' "$CLEANUP"
    printf -- '- Generated: `%s`\n' "$now"
    printf -- '- Log file: `%s`\n\n' "$LOG_FILE"
    printf '## Progress\n\n`%s`\n\n' "$progress"
    printf '## Checklist\n\n| Status | Check | Notes |\n| --- | --- | --- |\n'
    local i
    for (( i=0; i<${#CHECK_IDS[@]}; i++ )); do
      printf '| `%s` | %s | %s |\n' "${CHECK_STATUS[$i]}" "${CHECK_LABELS[$i]}" "$(escape_md "${CHECK_NOTES[$i]}")"
    done
  } > "$REPORT_PATH"
}

set_check() {
  local id="$1"; local status="$2"; local note="${3:-}"; local i color
  i="$(check_index "$id")"; CHECK_STATUS[$i]="$status"; CHECK_NOTES[$i]="$note"; write_report
  color="$C_BLUE"; [[ "$status" == "PASS" ]] && color="$C_GREEN"; [[ "$status" == "FAIL" ]] && color="$C_RED"; [[ "$status" == "SKIP" ]] && color="$C_YELLOW"
  log "${color}$(bar_for "$(completed_count)" "${#CHECK_IDS[@]}") [$status]${C_RESET} $id ${C_DIM}${note}${C_RESET}"
}

load_env_file() {
  if [[ -z "$ENV_FILE" || ! -f "$ENV_FILE" ]]; then
    log "${C_RED}Missing --env-file or file not found: $ENV_FILE${C_RESET}"
    exit 2
  fi
  set -a
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  set +a
  if [[ -n "${EXTERNAL_AZURE_CONFIG_DIR:-}" ]]; then
    local az_cfg="${EXTERNAL_AZURE_CONFIG_DIR/#\~/$HOME}"
    mkdir -p "$az_cfg"
    export AZURE_CONFIG_DIR="$az_cfg"
  fi
}

json_expr() {
  local expr="$1"
  python3 -c "import json,sys; d=json.load(sys.stdin); sys.exit(0 if ($expr) else 1)"
}

cleanup() {
  if [[ "$CLEANUP" == "true" ]]; then
    if python3 scripts/fabric-destroy.py --env-name "$ENV_NAME" --yes 2>&1 | tee -a "$LOG_FILE"; then
      set_check "cleanup" "PASS" "fabric-destroy.py completed"
    else
      set_check "cleanup" "FAIL" "fabric-destroy.py failed"
    fi
  else
    set_check "cleanup" "SKIP" "Resources kept for debugging."
  fi
}

trap 'write_report' EXIT

cat <<'BANNER' | tee -a "$LOG_FILE"

+---------------------------------------------------------------------+
| Azure AI Search Foundry IQ Live Knowledge Sources                   |
| Fabric-only E2E provisioning test                                   |
+---------------------------------------------------------------------+
BANNER
log "Log file: $LOG_FILE"
log "Report: $REPORT_PATH"
write_report

load_env_file
unset FABRIC_WORKSPACE_ID
unset FABRIC_ONTOLOGY_ID
unset FABRIC_LAKEHOUSE_ID

if bash scripts/external-tenant-login.sh --env-file "$ENV_FILE" --check-only 2>&1 | tee -a "$LOG_FILE"; then
  set_check "external_login" "PASS" "External tenant session active."
else
  set_check "external_login" "FAIL" "External tenant login is not active."
  exit 1
fi

missing_tools=""
for tool in azd az python3 curl; do
  if ! command -v "$tool" >/dev/null 2>&1; then missing_tools="$missing_tools $tool"; fi
done
if [[ -z "$missing_tools" ]]; then
  set_check "tools" "PASS" "azd, az, python3, curl"
else
  set_check "tools" "FAIL" "Missing:$missing_tools"
  exit 1
fi

if azd env select "$ENV_NAME" >/dev/null 2>&1; then
  :
else
  azd env new "$ENV_NAME" 2>&1 | tee -a "$LOG_FILE"
  azd env select "$ENV_NAME" >/dev/null
fi
azd env set DEPLOYMENT_MODE full 2>&1 | tee -a "$LOG_FILE"
azd env set FABRIC_CAPACITY_MODE "$FABRIC_CAPACITY_MODE" 2>&1 | tee -a "$LOG_FILE"
azd env set FABRIC_LOCATION "$FABRIC_LOCATION" 2>&1 | tee -a "$LOG_FILE"
if [[ -z "$FABRIC_CAPACITY_NAME" ]]; then
  FABRIC_CAPACITY_NAME="$(printf 'fab%s' "$ENV_NAME" | tr '[:upper:]' '[:lower:]' | tr -cd 'a-z0-9' | cut -c1-63)"
fi
azd env set FABRIC_CAPACITY_NAME "$FABRIC_CAPACITY_NAME" 2>&1 | tee -a "$LOG_FILE"
azd env set FABRIC_WORKSPACE_ID "" >/dev/null
azd env set FABRIC_ONTOLOGY_ID "" >/dev/null
azd env set FABRIC_LAKEHOUSE_ID "" >/dev/null
set_check "azd_env" "PASS" "$ENV_NAME"

PROVISION_RC=0
if python3 scripts/fabric-provision.py --env-name "$ENV_NAME" --fabric-location "$FABRIC_LOCATION" --capacity-mode "$FABRIC_CAPACITY_MODE" 2>&1 | tee -a "$LOG_FILE"; then
  set_check "provision" "PASS" "fabric-provision.py completed"
else
  PROVISION_RC=$?
  set_check "provision" "FAIL" "fabric-provision.py failed"
fi

SUMMARY_JSON="deployments/${ENV_NAME}/fabric-summary.json"
if [[ -f "$SUMMARY_JSON" ]]; then
  set_check "summary" "PASS" "$SUMMARY_JSON"
else
  set_check "summary" "FAIL" "Fabric summary missing."
  cleanup
  exit 1
fi

if json_expr 'all(d.get(k) for k in ["capacityId","workspaceId","lakehouseId","ontologyId"])' < "$SUMMARY_JSON"; then
  set_check "fabric_ids" "PASS" "Generated Fabric IDs are present."
else
  set_check "fabric_ids" "FAIL" "One or more Fabric IDs are missing."
fi

if json_expr 'len(d.get("tablesLoaded", [])) >= 7' < "$SUMMARY_JSON"; then
  set_check "tables" "PASS" "Airline Ops CSVs loaded into Lakehouse tables."
else
  set_check "tables" "FAIL" "Expected Lakehouse tables were not loaded."
fi

if json_expr 'd.get("ontologyValidation", {}).get("status") == "ok" and d.get("ontologyValidation", {}).get("partCount", 0) >= d.get("ontologyManifest", {}).get("partCount", 1)' < "$SUMMARY_JSON"; then
  set_check "ontology_definition" "PASS" "Ontology definition validates."
else
  set_check "ontology_definition" "FAIL" "Ontology definition validation failed."
fi

if json_expr 'd.get("graphValidation", {}).get("status") == "ok" and d.get("graphValidation", {}).get("probe", {}).get("rowCount", 0) > 0' < "$SUMMARY_JSON"; then
  set_check "graph_model" "PASS" "GraphModel is queryable."
else
  graph_note="$(python3 - "$SUMMARY_JSON" <<'PY'
import json
import sys
d=json.load(open(sys.argv[1]))
g=d.get("graphValidation", {})
print(f"status={g.get('status','')} readiness={g.get('queryReadiness','')} error={str(g.get('error',''))[:220]}")
PY
)"
  set_check "graph_model" "FAIL" "$graph_note"
fi

cleanup

if [[ "$PROVISION_RC" -ne 0 || "$(fail_count)" -gt 0 ]]; then
  exit 1
fi

log ""
log "${C_GREEN}+---------------------------------------------------------------------+${C_RESET}"
log "${C_GREEN}| Fabric E2E test completed                                           |${C_RESET}"
log "${C_GREEN}+---------------------------------------------------------------------+${C_RESET}"
log "Report: $REPORT_PATH"
